#!/bin/bash

set -e

. /usr/local/share/container-scripts/adjust-term

if [[ $CONTAINER_USER && $CONTAINER_GROUP ]]; then
	/usr/local/share/container-scripts/adjust-user "$CONTAINER_USER" "$CONTAINER_GROUP"
fi

exec "$@"
