FROM debian:stretch-slim

COPY no-install-suggests-recommends.apt.conf /etc/apt/apt.conf.d
RUN true \
	&& apt-get update \
	&& apt-get install -y mariadb-server-10.1 mariadb-client-10.1 rsyslog mycli mydumper less \
	&& find /var/lib/apt/lists /var/cache/apt/archives -type f -delete \
	&& mkdir /var/lib/container \
	&& tar -cC /var/lib/mysql/ . | gzip -9v > /var/lib/container/var_lib_mysql.tar.gz \
	&& rm -rf /var/lib/mysql \
	&& mkdir /var/lib/mysql \
	&& true

COPY etc/rsyslog.d/stderr.conf /etc/rsyslog.d/
COPY scripts/adjust-user scripts/adjust-term scripts/entrypoint scripts/exec /usr/local/share/container/scripts/
COPY entrypoint/mysql /usr/local/share/container/entrypoint/
COPY bin/mysql bin/mycli bin/myloader /usr/local/share/container/bin/
COPY etc/mysql/mariadb.conf.d/99-docker.cnf /etc/mysql/mariadb.conf.d/99-docker.cnf
ENV CONTAINER_USER mysql
ENV CONTAINER_GROUP mysql

EXPOSE 3306
ENTRYPOINT ["/usr/local/share/container/scripts/entrypoint", "mysql"]
CMD ["/usr/bin/mysqld_safe"]
