version: '3.4'

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

x-nginx: &_nginx-base
  build:
    args:
      - http_proxy
      - NGINX_UPGRADE=1
    context: .
    dockerfile: Dockerfile.nginx
    network: build
  image: production-nginx
  logging:
    <<: *_logging

x-postfix: &_postfix-base
  build:
    args:
      - http_proxy
    context: .
    dockerfile: Dockerfile.postfix
    network: build
  cap_add:
    - SYS_PTRACE
  domainname: localdev
  image: production-postfix
  logging:
    <<: *_logging
  restart: always
  volumes:
    - home:/home

networks:
  default:
  mail:
    external:
      name: mail
  build:
    external:
      name: build
  nginx:
    external:
      name: nginx

volumes:
  home:

  nginxproxy-conf:
  nginxproxy-vhost:
  nginxproxy-html:

services:
  nginx:
    <<: *_nginx-base
    container_name: nginx
    networks:
      nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - nginxproxy-conf:/etc/nginx/conf.d:ro
      - nginxproxy-vhost:/etc/nginx/vhost.d:ro
      - nginxproxy-html:/usr/share/nginx/html
      - /srv/ssl-certificates:/etc/nginx/certs:ro

  dockergen:
    build:
      args:
        - http_proxy
      context: .
      dockerfile: Dockerfile.dockergen
      network: build
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    image: production-dockergen
    networks:
      nginx:
    restart: always
    volumes:
      - nginxproxy-conf:/etc/nginx/conf.d:rw
      - nginxproxy-vhost:/etc/nginx/vhost.d:ro
      - /srv/ssl-certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - nginxproxy-vhost:/etc/nginx/vhost.d:rw
      - nginxproxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/ssl-certificates:/etc/nginx/certs:rw

  postfix:
    <<: *_postfix-base
#    environment:
#      POSTFIX_CATCHALL: 'true'
    networks:
      mail:
        aliases:
          - smtp
          - mail # for ssmtp

