FROM debian:jessie-slim

COPY etc/apt/apt.conf.d/no-install-suggests-recommends.apt.conf /etc/apt/apt.conf.d/
RUN true \
	&& apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server-5.5 mysql-client-5.5 rsyslog less \
	&& find /var/lib/apt/lists /var/cache/apt/archives -type f -delete \
	&& mkdir /var/lib/container \
	&& tar -cC /var/lib/mysql/ . | gzip -9v > /var/lib/container/var_lib_mysql.tar.gz \
	&& rm -rf /var/lib/mysql \
	&& mkdir /var/lib/mysql \
	&& true

COPY etc/rsyslog.d/stderr.conf /etc/rsyslog.d/
COPY scripts/adjust-user scripts/adjust-term scripts/entrypoint scripts/exec /usr/local/share/container/scripts/
COPY entrypoint/mysql /usr/local/share/container/entrypoint/
COPY bin/mysql bin/mycli bin/myloader /usr/local/share/container/bin/
ENV CONTAINER_USER mysql
ENV CONTAINER_GROUP mysql

EXPOSE 3306
ENTRYPOINT ["/usr/local/share/container/scripts/entrypoint", "mysql"]
CMD ["/usr/bin/mysqld_safe"]
