FROM node:11-stretch as app-node
ARG NPM_VERSION=latest

COPY no-install-suggests-recommends.apt.conf /etc/apt/apt.conf.d
RUN true \
	&& apt-get update \
	&& apt-get install -y gosu \
	&& find /var/lib/apt/lists /var/cache/apt/archives -type f -delete \
	&& npm install -g npm@$NPM_VERSION \
	&& true
