FROM debian:stretch-slim

ARG NGINX_UPGRADE

EXPOSE 80 443

COPY etc/apt/sources.list.d/stretch-backports.list etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update \
	&& apt-get install -t stretch-backports -y nginx libnginx-mod-http-lua \
	&& ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log \
	&& rm /etc/nginx/sites-enabled/default \
	&& sed -e 's/\(ssl_protocols\|ssl_prefer_server_ciphers\)/#\1/' -i /etc/nginx/nginx.conf \
	&& mkdir /etc/nginx/modules.d \
	&& find /var/cache/apt /var/lib/apt -type f -delete \
	&& true

COPY scripts/adjust-user scripts/adjust-term scripts/entrypoint scripts/exec /usr/local/share/container/scripts/
COPY healthcheck/nginx /usr/local/share/container/healthcheck/
COPY etc/nginx/conf.d/00-increase-client-max-body-size.conf /etc/nginx/conf.d/00-increase-client-max-body-size.conf
COPY etc/nginx/modules-enabled/99-docker-modules.conf /etc/nginx/modules-enabled/99-docker-modules.conf
HEALTHCHECK --interval=15s CMD ["/usr/local/share/container/healthcheck/nginx"]

ENTRYPOINT ["/usr/local/share/container/scripts/entrypoint"]
CMD ["nginx", "-g", "daemon off;"]
