ARG VERSION=latest
ARG IMAGE_PREFIX=docker.brainfood.com/shared
FROM $IMAGE_PREFIX/jessie-slim-base:$VERSION AS image-base

RUN true \
	&& ulimit -n 2048 \
	&& apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server-5.5 mysql-client-5.5 rsyslog less \
	&& find /var/lib/apt/lists /var/cache/apt/archives -type f -delete \
	&& mkdir /var/lib/container \
	&& tar -cC /var/lib/mysql/ . | gzip -9v > /var/lib/container/var_lib_mysql.tar.gz \
	&& rm -rf /var/lib/mysql \
	&& mkdir /var/lib/mysql \
	&& true

FROM $IMAGE_PREFIX/jessie-slim-script:$VERSION AS script-base

COPY etc/rsyslog.d/stderr.conf /etc/rsyslog.d/
COPY entrypoint/mysql /usr/local/share/container/entrypoint/
COPY bin/mysql bin/mycli bin/myloader /usr/local/share/container/bin/

FROM image-base AS final-output
COPY --from=script-base / /

ENV CONTAINER_USER mysql
ENV CONTAINER_GROUP mysql

EXPOSE 3306
ENTRYPOINT ["/usr/local/share/container/scripts/entrypoint", "mysql"]
CMD ["/usr/bin/mysqld_safe"]
