version: '3.4'

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

networks:
  default:
  mail:
    external:
      name: mail-prod
  build:
    external:
      name: build

volumes:
  home:

services:
  postfix:
    cap_add:
      - SYS_PTRACE
    domainname: localdev
#    environment:
#      POSTFIX_CATCHALL: 'true'
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}postfix:${IMAGE_TAG_POSTFIX:-dev}
    logging:
      <<: *_logging
    networks:
      mail:
        aliases:
          - smtp
          - mail # for ssmtp
    restart: always
    volumes:
      - home:/home

