#!/bin/bash

set -e

target_home="$(getent passwd "$CONTAINER_USER" | cut -f 6 -d :)"

if [[ $http_proxy =~ ^([^:]+)://([^/:]*)(:([0-9]+?))?(/.*)?$ ]]; then
	http_proxy_protocol="${BASH_REMATCH[1]}"
	http_proxy_domain="${BASH_REMATCH[2]}"
	http_proxy_port="${BASH_REMATCH[4]}"
fi

if [[ $http_proxy ]]; then
	mkdir -p "$target_home/.m2"
	cat > "$target_home/.m2/settings.xml" << _EOF_
<settings>
  <proxies>
   <proxy>
      <id>app-build-proxy</id>
      <active>true</active>
      <protocol>${http_proxy_protocol}</protocol>
      <host>${http_proxy_domain}</host>
      <port>${http_proxy_port}</port>
    </proxy>
  </proxies>
</settings>
_EOF_
	mkdir -p "$target_home/.gradle"
	cat > "$target_home/.gradle/gradle.properties" << _EOF_
systemProp.http.proxyHost=${http_proxy_domain}
systemProp.http.proxyPort=${http_proxy_port}
#systemProp.http.proxyUser=de\\username
#systemProp.http.proxyPassword=xxx
_EOF_
fi

if [[ $LOCALDEV_NEXUS ]]; then
	mkdir -p "$target_home/.gradle/init.d"
	cat > "$target_home/.gradle/init.d/nexus.gradle" << _EOF_
allprojects {
  repositories {
     maven {
        url "http://${LOCALDEV_NEXUS}/maven-public"
     }
     jcenter {
        url "http://${LOCALDEV_NEXUS}/repository/jcenter"
     }
  }
}
_EOF_
fi

# This has already been run once, but since new files have been created
# in $HOME, the permissions need to be fixed.
/usr/local/share/container/scripts/adjust-user "$CONTAINER_USER" "$CONTAINER_GROUP"

exec "$@"
