#!/bin/bash

# This script will configure npm to run inside docker.  The only
# feature it currently supports is the use of a local mirror
# repository.

set -x
if [[ $(which npm) ]]; then
	if [[ $HOSTING_NEXUS ]]; then
		npm config -g set registry http://${HOSTING_NEXUS}/repository/npm-group
	fi
	gosu $CONTAINER_USER npm config set prefix /home/node/.npm-prefix
	if [[ -e package.json ]]; then
		if [[ $NPM_AUTO_INSTALL ]]; then
			gosu $CONTAINER_USER npm install
		fi
		if [[ $NPM_AUTO_RUN ]]; then
			gosu $CONTAINER_USER npm run "$NPM_AUTO_RUN"
		fi
	fi
fi

ulimit -n 8192

exec "$@"
