version: '3.4'

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

networks:
  default:

volumes:
  bind9-etc:

services:
  bind9:
    environment:
      MAP_USER:
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}bind9:${IMAGE_TAG_BIND9:-dev}
    logging:
      <<: *_logging
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always
    volumes:
      - type: volume
        source: bind9-etc
        target: /etc/bind
        volume:
          nocopy: false

  file-access:
    depends_on:
      - bind9
    environment:
      MAP_USER:
      BACKUP_1_LOCATION: /srv/app/volumes/bind9-etc
      BACKUP_1_FREQUENCY: daily
      BACKUP_1_METHOD: duplicity
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}file-access:${IMAGE_TAG_FILE_ACCESS:-dev}
    logging:
      <<: *_logging
    restart: always
    volumes:
      - bind9-etc:/srv/app/volumes/bind9-etc
