#!/bin/bash

if [[ $$ -eq 1 ]] && which dumb-init > /dev/null; then
	exec dumb-init -- "$0" "$@"
	echo "Failure re-execing dumb-init!" 1>&2
	exit 1
fi

set -e

. /usr/local/share/container/scripts/adjust-term

if [[ $CONTAINER_USER && $CONTAINER_GROUP ]]; then
	/usr/local/share/container/scripts/adjust-user "$CONTAINER_USER" "$CONTAINER_GROUP"
fi

if [[ -e /container-init.d/* ]]; then
	for s in /container-init.d/*; do
		$s
	done
fi

if [[ -e /etc/init.d/rsyslog ]]; then
	/etc/init.d/rsyslog start
fi

if [[ -e /etc/init.d/ssh ]]; then
	/etc/init.d/ssh start
fi

exec "$@"
