#!/bin/bash

set -e

cmd="$1"
shift

if [[ $cmd =~ ^/ ]]; then
	if [[ -x $cmd ]]; then
		exec "$cmd" "$@"
		exit 1
	fi
	echo "$cmd is not found or not executable" 1>&2
	exit 1
fi
declare -a locations=(
	"/usr/local/share/container/bin"
	"/srv/app/container-scripts/bin"
)
for location in "${locations[@]}"; do
	if [[ -e $location/$cmd ]]; then
		exec "$location/$cmd" "$@"
		exit 1
	fi
done
echo "Could not find script '$cmd'!" 1>&2
exit 1
