version: '3.4'

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

networks:
  default:
  build:
    external:
      name: build
  nginx:
    external:
      name: nginx

volumes:
  nginxproxy-conf:
  nginxproxy-vhost:
  nginxproxy-html:

services:
  nginx:
    container_name: nginx
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}nginx:${IMAGE_TAG_NGINX:-dev}
    logging:
      <<: *_logging
    networks:
      nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - nginxproxy-conf:/etc/nginx/conf.d:ro
      - nginxproxy-vhost:/etc/nginx/vhost.d:ro
      - nginxproxy-html:/usr/share/nginx/html
      - /srv/ssl-certificates:/etc/nginx/certs:ro

  dockergen:
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    depends_on:
      - nginx
    environment:
      - DEFAULT_HOST
    image: bf-dockergen
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}dockergen:${IMAGE_TAG_DOCKERGEN:-dev}
    networks:
      nginx:
    restart: always
    volumes:
      - nginxproxy-conf:/etc/nginx/conf.d:rw
      - nginxproxy-vhost:/etc/nginx/vhost.d:ro
      - /srv/ssl-certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  self-signed:
    depends_on:
      - nginx
    image: sebastienheyd/self-signed-proxy-companion
    networks:
      default:
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - ROOT_CERT=/srv/certs/root.crt
      - ROOT_KEY=/srv/certs/root.key
    volumes:
      - /srv/ssl-certificates:/etc/nginx/certs:rw
      - /srv/root-ssl-certificates:/srv/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  letsencrypt:
    environment:
      - DEFAULT_EMAIL
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    depends_on:
      - nginx
      - dockergen
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - nginxproxy-vhost:/etc/nginx/vhost.d:rw
      - nginxproxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/ssl-certificates:/etc/nginx/certs:rw

