version: '3.4'

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

x-postfix: &_postfix-base

networks:
  default:
  mail:
    external:
      name: mail-dev
  build:
    external:
      name: build
  nginx:
    external:
      name: nginx

volumes:
  home:

services:
  roundcube:
    environment:
      CERT_NAME: ${HOSTING_VHOST_CERT_NAME}
      VIRTUAL_HOST: mail${HOSTING_VHOST_SUFFIX}
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}roundcube:${IMAGE_TAG_ROUNDCUBE:-dev}
    logging:
      <<: *_logging
    networks:
      default:
      nginx:
    restart: always

  dovecot:
    domainname: localdev
    environment:
      - DOVECOT_HOSTUSER_PASSWORD
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}dovecot:${IMAGE_TAG_DOVECOT:-dev}
    logging:
      <<: *_logging
    networks:
      default:
        aliases:
          - imap
    restart: always
    volumes:
      - type: volume
        source: home
        target: /home
        volume:
          nocopy: false

  postfix:
    cap_add:
      - SYS_PTRACE
    domainname: localdev
    environment:
      POSTFIX_CATCHALL: 'true'
    image: ${IMAGE_PREFIX:-docker.brainfood.com/shared/}postfix:${IMAGE_TAG_POSTFIX:-dev}
    logging:
      <<: *_logging
    networks:
      mail:
        aliases:
          - smtp
          - mail # for ssmtp
    restart: always
    volumes:
      - home:/home

